version: "3.2"

services:
  node-app:
    depends_on:
      - redis

  redis:
    container_name: redis
    image: redis:5.0.7
    networks:
      - appnetworkname
    ports:
      - 6379:6379


networks:
  appnetworkname:
    driver: bridge

volumes:
    mysql-data-node-app:
    elasticsearch:

